os: linux
language: node_js

jobs:
  include:
  - stage: build and deploy
    if: ((branch = master AND type != pull_request) AND fork = false)
    script:
    - npm run lint || travis_terminate 1
    - npm run build || travis_terminate 1
    after_success:
    - npm run semantic-release || travis_terminate 1

#deploy:
#  provider: pages
#  cleanup: false
#  github_token: $GITHUB_TOKEN  # #Set in the settings page of #your repository, as a secure #variable
#  keep_history: true
#  on:
#    branch: master
