os: linux
language: node_js

jobs:
  include:
  - stage: build and deploy
    if: ((branch = master AND type != pull_request) AND fork = false)
    script:
    - npm run lint || travis_terminate 1
    - npm run build || travis_terminate 1
    after_success:
    - npm run semantic-release || travis_terminate 1
    - netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir
      ./dist/ || travis_terminate 1
