os: linux
language: node_js

jobs:
  include:
  - stage: build and deploy
    if: ((branch = master AND type != pull_request) AND fork = false)
    script:
    - npm run lint || travis_terminate 1
    - npm run build || travis_terminate 1
    after_success:
    - npm run semantic-release || travis_terminate 1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: ./dist
  repo: feerglas/feiertach
  on:
    branch: master
